[package]
name = "urbanite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
noise = "0.8"
futures-lite = "1.13"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
